language: java
sudo: false
jdk:
- oraclejdk8
before_script:
- chmod +x gradlew
script:
- "./gradlew check"
- "./gradlew codeCoverageReport"
- sonar-scanner
after_success:
- bash <(curl -s https://codecov.io/bash)
addons:
  sonarcloud:
    organization: triberay
    token:
      secure: RpwhCwd59bvbBFxKAmzHGyXwmBSRg6pOLdvoaQNBQHeNVfZ9GFFPRNZAHtEFQhwz5rnzIzPgWnN+Qb5A7Cc07qti9uPXM/ard7OrvX60qv4zy3j/PWOSA8+zEy/NiBMhtTnnZNICu5P47b4+G5E/yDQSfL2a2RcDGo3oGlyTkvJq+STtmMFJpLWc2RBteyNxj5haY37FTxh1mCPx0wXXy8CQ2RjbFDsFErhPSUHjBwjcNJ/Awkn/JNdmv6Gy40tAIkFA7rIsRhjnby//vM/ImzLJOVb6O7m+HJfKMNQ2aGsdhHYxUExIiP32iQPi7MJJ2nfo6TwVq6/WflwPTzBvBAp1edNfq9pSy1Srn1FiB4Qm1d/OvByOtPH26UFJvAHDvZP1f2NyFTdqJOdwKYacceQBSsMvzq9b3pvx0z4g4cAgBCdiUJP0r0IFiqQ0A6/OYykFvo1g2Q+fGNs0AAYietZTrpzlYzP1DHOoR//ccNjDJXffapiLeg4GbaD4NvYVmAKyvfRevkQv2IbuWXSrWnfDeIu77yBhBu97xF1GwSL89cOoGTGNCzJdakwO83cEXGUSMNSLYT2HTbYlhDc+61wtErTwVGhfmpmsP4Qx3qZ2Hivx+ePAOyLAPL36BlDJPj6LxJmvNa5/AXQZYuYcGqc1j1WUNsP7mqhDf6/AMwM=
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  slack:
    rooms:
      secure: eyQQj1039up9pF3HR6QLoe/GjgvV1aMIovoHAXaRFA6mp0nr34P5Nb7eYiAkg6RlMzq/0G5fTXVToUhB19LyfT2+w+Bt9k5hqmhqjQdekH/LTus4pVqx9LXpF+88sYrnZY/f8D1CpXT5z1bvLTwfVkoeyTSlkUIUkRKuHPkWCFmtaUwqH5bRITc2zolKcTD3aiQ62e+clp2hfy7qy2+EdK27YcbSSztI4BCBMAqp5b5U8vYPSbtnV9YtWGKpMfperQkdNpKLFLzEQphMVaY4pN3BceKqF8hA8N0OCQn3ryZIg3m0ZSMRF9ZfyYSskCWgaWNoLnXMKJVnehPG7SJCbqBp7hO033rt+pD0Li+vxcBfS8OJNPSU6jWnAu9skHBpW4UMMw5CaQTU213tStc6sXNcWP2nOjC1RkmODavebxUORfvW8oNWhkakCvr6gwjtMbNwxrq17C6VvPOUwFEzdWfYvie9NqlGuTGCIHNfzImUAK6mr8J8wdAdlRYZwNLkNCWqrnQztCRKFIiCPd+Z9IbbQg7C+eIo9+5QJO8DxkiLQjOigojFe8ni9c7U8QlTMNEMwA6pjqdcn/7JU6dVcGxWw7BzVAUBc+YRTElServnJndPGXBU+RjOkUiLL+EYNEtWtTloWN7wtiKw3emGgdLJ1cN3zrSHWTXieNvFXx8=
